title: 部落格

collections:
  authors:
    output: true

defaults:
# _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _authors
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # /
  - scope:
      path: ""
    values:
      layout: "default"
