locale                    : "en-US"
title                     : "木下悠人"
author                    : "velskii"
github_username           : "velskii"
rss                       : "rss"
show_excerpts             : true
email                     : "velski@yahoo.com"
description               : "this is a simple blog website"
permalink                 : pretty
include:
  - _pages

collections:
  authors:
    output: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _authors
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # /
  - scope:
      path: ""
    values:
      layout: "default"